### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by gpcola** [craftwerkberlin/bs5-post-product-slider#1]
After installing this plugin my site was unusable, with any url request resulting in an infinite loop. Is it possible  that the latest update has introduced an issue?

I'm using this with bootScore 5 and bootCommerce 5 Child Theme.

**Comment by crftwrk** [comment]
Hmm, usually not. Because update only add child-pages feature to it. 

I would do this to reproduce: 

1. Uninstall plugin and check that there is no second installation
2. Download plugin, unzip, remove -main branch from folder
3. Zip again and upload it.

If that not works, then downgrade to previous version https://github.com/craftwerkberlin/bs5-post-product-slider/commit/8620b9d3da5109b61c8cf5f5f8d11437b8ad0bb4

I do not know what you do on your site. But maybe it can be something with plugin folder name and/or template overrides in theme. 

For example plugin folder must be bs5-post-product-slider. If you download via Guthub, folder is bs5-post-product-slider-main. In this case you have plugin twice and get an error.

This are just ideas, but I would start with that to check.

However, I‘m working on a new swiper plugin right now which has more features and improvements. The new plugin will replace this one here.

Does that help?

**Comment by crftwrk** [comment]
This plugin is replaced by new one https://github.com/craftwerkberlin/bs5-swiper. Uninstall bs5-post-product-slider first and then install new plugin. Check https://bootscore.me/documentation/bs-swiper/ for new shortcodes.
